cms_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import TemplateView
from quotes.views import Register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/success/', TemplateView.as_view(template_name="registration/success.html"), name='register-success'),
    path('register/', Register.as_view(), name='register'),
    path('quote/', include('quotes.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("", views.index, name='index'),
    path('', views.index, {'pagename': ''} ,name='home'),
    path('contact', views.contact, name='contact'),
    path('<str:pagename>', views.index, name='index'),

]

quotes/urls.py
from django.urls import path

from . import views
from .views import QuoteListView, QuoteDetailView

urlpatterns = [
    path("", views.quote_req, name='quote-request'),
    path("show/<int:pk>", QuoteDetailView.as_view(), name='quote-detail'),
    path("show", QuoteListView.as_view(), name='quote-list'),
]

pages/models.py
from django.db import models

# Create your models here.
class Page(models.Model):

    title = models.CharField(max_length=60)
    permalink = models.CharField(max_length=12, unique=True)
    update_date = models.DateTimeField('Last Updated')
    body_text = models.TextField('Page Content', blank=True)

    def __str__(self):
        return self.title

quotes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
STATUS_CHOICE = (
        ('NEW', 'New Site'),
        ('EX', 'Existing Site'),
    )

PRIORITY_CHOICE = (
        ('U', 'Urgent - 1 week or Less'),
        ('N', 'Normal - 2 to 4 weeks'),
        ('L', 'Low - Still Researching'), 
    )

class Quote(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=60, blank=True)
    company = models.CharField(max_length=60, blank=True)
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    email = models.EmailField()
    web = models.URLField(blank=True)
    description = models.TextField()
    sitestatus = models.CharField(max_length=20, choices=STATUS_CHOICE)
    priority = models.CharField(max_length=40, choices=PRIORITY_CHOICE)
    jobfile = models.FileField(upload_to='uploads/', blank=True)
    submitted = models.DateField(auto_now_add=True)
    quotedate = models.DateField(blank=True, null=True)
    quoteprice = models.DecimalField(decimal_places=2, max_digits=7, blank=True, default=0)
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE) 

    def __str__(self):
        return str(self.id)

pages/forms.py
from django import forms

class ContactForm(forms.Form):
    your_name = forms.CharField(label='Your Name', max_length=100)
    email = forms.EmailField(label='Your email address', required=False)
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

quotes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Quote

class QuoteForm(ModelForm):
    required_css_class = 'required'
    class Meta:
        model = Quote
        fields = [
            'name', 'position', 'company', 'address', 
            'phone', 'email', 'web', 'description',
            'sitestatus', 'priority', 'jobfile'
        ]

pages/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, get_connection

from datetime import datetime

from .models import Page
from .forms import ContactForm


# Create your views here.
def index(request, pagename):
    pagename = f'/{pagename}'
    page = get_object_or_404(Page, permalink=pagename)
    current_year = datetime.now().strftime('%Y')
    context = {
        'page_title' : page.title,
        'page_content' : page.body_text,
        'page_last_updated' : page.update_date,
        'page_list' : Page.objects.all(),
        'current_year' : current_year,
    }
    
    #assert False
    
    return render(request, 'pages/index.html', context)


def contact(request):
    submitted = False
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            #assert False
            # sending email to console for testing
            con = get_connection('django.core.mail.backends.console.EmailBackend')
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
                connection=con
            )

            return HttpResponseRedirect('/contact?submitted=True')
    else:
        form = ContactForm()
        if 'submitted' in request.GET:
            submitted = True

    context = {
        'form' : form,
        'page_list' : Page.objects.all(),
        'submitted' : submitted,
    }

    return render(request, 'pages/contact.html', context)

quotes/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Authentication
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

from .models import Quote
from .forms import QuoteForm
from pages.models import Page


# User Registration
class Register(CreateView):
    # properties assignment
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register-success')
    # method
    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.success_url)


class QuoteListView(LoginRequiredMixin,ListView):
    login_url = reverse_lazy('login')
    #model = Quote
    context_object_name = 'all_quotes' # naaming the object that will be passed over to the template

    # Mixins
    # Only extract the list of quotes for the currently logged-in user
    def get_queryset(self):
        return Quote.objects.filter(username = self.request.user)
    # Mixins
    def get_context_data(self, **kwargs):
        context = super(QuoteListView, self).get_context_data(**kwargs)
        context['page_list'] = Page.objects.all()
        return context

class QuoteDetailView(LoginRequiredMixin,DetailView):
    login_url = reverse_lazy('login')
    #model = Quote
    context_object_name = 'quote'

    #Mixin
    # Only extract the individual quote for current logged-in user
    def get_queryset(self):
        return Quote.objects.filter(username = self.request.user)
    
    # Mixin
    def get_context_data(self, **kwargs):
        context = super(QuoteDetailView, self).get_context_data(**kwargs)
        context['page_list'] = Page.objects.all()
        return context

@login_required(login_url=reverse_lazy('login')) # prevent unauthorized access
def quote_req(request):
    submitted = False
    if request.method == 'POST':
        form = QuoteForm(request.POST, request.FILES)
        if form.is_valid():
            quote = form.save(commit=False)
            try:
                quote.username = request.user
            except Exception:
                pass
            quote.save()
            return HttpResponseRedirect('/quote/?submitted=True')
    else:
        form = QuoteForm()
        if 'submitted' in request.GET:
            submitted = True
    context = {
        'form' : form,
        'page_list' : Page.objects.all(),
        'submitted' : submitted
    }
    return render(request, 'quotes/quote.html', context)
    

cms_site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css?v=1.0" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>{% block title %}{% endblock %} :: Demo CMS</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Django CMS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    {% block sitenav %}
                        {% for page in page_list %}
                            <li class="nav-item"><a class="nav-link" href="{{ page.permalink }}"> {{ page.title }} </a></li>
                        {% endfor %}
                        <li class="nav-item"><a class="nav-link" href="/contact"> Contact Us </a></li>
                        <li class="nav-item"><a class="nav-link" href="/quote/"> Get a Quote </a></li>
                        <li class="nav-item"><a class="nav-link" href="/quote/show"> Show Quotes </a></li>
                    {% endblock sitenav %}
                </ul>

            </div>
            <span class="justify-content-right">
                {% if user.is_authenticated%}
                    <i class="text-light">Hello, {{ user.username }}</i>
                    <a class="btn btn-outline-warning my-2 my-sm-0" href="{% url 'logout' %}?next=/">Logout</a>
                {% else %}
                <i class="text-light">Not logged in</i>
                    <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'login' %}?next=/">Login</a>
                {% endif %}
            </span>

        </div>
    </nav>
    <main class="mt-5">
        {% if messages %}
            {% for message in messages %}
                <div class="row amber lighten-3">
                    <div class="grid-example col s8 offset-s4"><span class="flow-text">{{ message }}</span></div>
                </div>
            {% endfor %}
        {% endif %}

        <div class="container">
            {% block content %}{% endblock %}
        </div> 
    </main>
   
    <footer>
        <div class="mt-5">
          <div class="container">
            &copy; {{ current_year }} Demo CMS | All Rights Reserved 
          </div>
        </div>
    </footer>

    <!--JavaScript at end of body for optimized loading-->
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src={% static 'js/app.js' %}></script>
</body>
</html>


       

pages/templates/pages/contact.html
<!-- pages/templates/pages/contact.html -->
{% extends 'base.html' %}

{% block title %} Contact Us {% endblock title %}

{% block content %}
<h1>Contact Us</h1>
{% if submitted %}
    <div class="alert alert-success" role="alert">
        Your message was submitted successfully. Thank you.
    </div>

{% else %}
    <form method="POST" action="" novalidate>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Submit"></td>
            </tr>
        </table>
    </form>
{% endif %}

{% endblock content %}

pages/templates/pages/index.html
<!-- pages/templates/pages/home.html -->
{% extends 'base.html' %}

{% block title %} {{ page_title }} {% endblock title %}

{% block content %}
{% autoescape off%}
{{ page_content }}
{% endautoescape %}
<p>Page last updated on {{ page_last_updated|date:'D d F Y' }}</p>
{% endblock content%}

quotes/templates/quotes/quote.html
{% extends 'base.html' %}

{% block title%} Quote Request {% endblock title%}

{% block content %}
<h1>Quote Request</h1>

{% if submitted %}
    <div class="alert alert-success" role="alert">
        Your message was submitted successfully. Thank you.
    </div>
{% else %}
    <form action="" enctype="multipart/form-data" method="POST" novalidate>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Submit"></td>
            </tr>
        </table>
    </form>
{% endif %}
{% endblock content %}

quotes/templates/quotes/quote_detail.html
{% extends 'base.html' %}

{% block title %}All Quotes{% endblock title %}

{% block content %}
    <h1>All Quotes</h1>

    <table class="table table-striped">
        <tr><td>Id</td><td>{{ quote.id }}</td></tr>
        <tr><td>Name</td><td>{{ quote.name }}</td></tr>
        <tr><td>Company</td><td>{{ quote.company }}</td></tr>
        <tr><td>Email</td><td>{{ quote.email }}</td></tr>
        <tr><td>Web Address</td><td>{{ quote.web }}</td></tr>
        <tr><td>Job Description</td><td>{{ quote.description }}</td></tr>
        <tr><td>Site Status </td><td>{{ quote.get_sitestatus_display }}</td></tr>
        <tr><td>Priority </td><td>{{ quote.get_priority_display }}</td></tr>
        
        <tr><td>Submitted Date</td><td>{{ quote.submitted|date:"m-d-y" }}</td></tr>
        <tr><td>Quote Date</td><td>{{ quote.quotedate|date:"m-d-y"|default:"panding" }}</td></tr>
        <tr><td>Quote Price</td><td>{{ quote.quoteprice|default:"--" }}</td></tr>
    </table>
    <p><a href="../show">Back to quote list</a></p>
{% endblock content %}

quotes/templates/quotes/quote_list.html
{% extends 'base.html' %}

{% block title %}All Quotes{% endblock title %}

{% block content %}
    <h1>All Quotes</h1>

    <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Client Name</th>
            <th scope="col">Company</th>
            <th scope="col">Submitted</th>
            <th scope="col">Quoted</th>
            <th scope="col">Quote Price</th>
          </tr>
        </thead>
        <tbody>
            {% for quote in all_quotes %}
            <tr>
                <th scope="row"><a href="show/{{ quote.id }}">{{ quote.id }}</a></th>
                <td>{{ quote.name }}</td>
                <td>{{ quote.company}}</td>
                <td>{{ quote.submitted|date:'m-d-y' }}</td>
                <td>{{ quote.quotedate|date:'m-d-y'|default:'pending' }}</td>
                <td>{{ quote.quoteprice|default:'--' }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>


{% endblock content %}